version: 2
registries:
  github-octocat:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.DEPENDABOT_TOKEN }}
updates:
  - package-ecosystem: "npm"
    directory: "/front-end"
    schedule:
      interval: "weekly"
    registries:
      - registry: github-octocat

  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
