version: '3'
services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True # si vous êtes en mode développement
    volumes:
      - ./backend:/code  # Ici, je suppose que votre code source est dans ./backend
      - /Users/ousmanekonate/Dev/interactive_portfolio/front-end/public:/code

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - backend

  frontend:
    build: ./front-end
    command: npm start
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .docker.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
