name: 🧪 Checking PR Health

on:
    pull_request:
      types: [opened, reopened, synchronize, review_requested, ready_for_review]

jobs:
  lint:
    name: 🫧 Linting Files
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files

  docker:
    name: 👷🏿 Build Docker compose
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Docker Compose
        env:
            SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
            SQL_ENGINE: django.db.backends.postgresql
            DB_NAME: ${{ vars.DB_NAME }}
            DB_USER: ${{ vars.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DB_HOST: db
            DB_PORT: 5432
            DJANGO_ALLOWED_HOSTS: '0.0.0.0'
            ALLOWED_HOSTS: '0.0.0.0'
        run: docker-compose build
